/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abibannunziatagitafile;

/**
 *
 * @author annunziata.christian
 */
public class FrameGita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGita.class.getName());
    private GestioneStudenti gestione = new GestioneStudenti();
    private String ultimoRecordInserito = "";
    /**
     * Creates new form FrameGita
     */
    public FrameGita() {
    initComponents();
    caricaComboGite();

    btnLeggiTutti.addActionListener(e -> leggiTutti());
    btnCercaPerGita.addActionListener(e -> cercaPerGita());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCercaGita = new javax.swing.JLabel();
        lblIscritto = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        lblNomeGita = new javax.swing.JLabel();
        lblDestinazione = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        txtClasse = new javax.swing.JTextField();
        txtDestinazione = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtNomeGita = new javax.swing.JTextField();
        chkIscritto = new javax.swing.JCheckBox();
        btnInserisci = new javax.swing.JButton();
        btnLeggiTutti = new javax.swing.JButton();
        btnCercaPerGita = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnIndietro = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnSvuotaTutti = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnSvuotaRecordSelezionato = new javax.swing.JButton();
        btnSvuotaCampi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblCercaGita.setText("Cerca Gita");

        lblIscritto.setText("Iscritto");

        lblCosto.setText("Costo");

        lblCognome.setText("Cognome");

        lblClasse.setText("Classe");

        lblNomeGita.setText("Nome Gita");

        lblDestinazione.setText("Destinazione");

        txtDestinazione.setToolTipText("");
        txtDestinazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinazioneActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtNomeGita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeGitaActionPerformed(evt);
            }
        });

        chkIscritto.setSelected(true);
        chkIscritto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIscrittoActionPerformed(evt);
            }
        });

        btnInserisci.setText("Inserisci Record");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });

        btnLeggiTutti.setText("Leggi Tutti");
        btnLeggiTutti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeggiTuttiActionPerformed(evt);
            }
        });

        btnCercaPerGita.setText("Cerca per Gita");
        btnCercaPerGita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaPerGitaActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jScrollPane2.setViewportView(jScrollPane1);

        btnIndietro.setText("Indietro");
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnSvuotaTutti.setText("Svuota tutti i Records");
        btnSvuotaTutti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvuotaTuttiActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        btnSvuotaRecordSelezionato.setText("Svuota Record Selezionato");
        btnSvuotaRecordSelezionato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvuotaRecordSelezionatoActionPerformed(evt);
            }
        });

        btnSvuotaCampi.setText("Svuota Campi");
        btnSvuotaCampi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvuotaCampiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblClasse)
                                    .addComponent(lblCognome)
                                    .addComponent(lblCosto)
                                    .addComponent(lblCercaGita)
                                    .addComponent(lblNomeGita)
                                    .addComponent(lblDestinazione))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtCognome)
                                    .addComponent(txtClasse)
                                    .addComponent(txtCosto)
                                    .addComponent(txtNomeGita)
                                    .addComponent(txtDestinazione)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 12, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIscritto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkIscritto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLeggiTutti)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnIndietro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCercaPerGita)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSvuotaTutti)
                                .addGap(32, 32, 32)
                                .addComponent(btnSvuotaRecordSelezionato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSvuotaCampi))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserisci)
                            .addComponent(btnLeggiTutti)
                            .addComponent(btnIndietro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCognome)
                            .addComponent(txtCognome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasse)
                            .addComponent(txtClasse, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeGita)
                            .addComponent(txtNomeGita, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDestinazione)
                            .addComponent(txtDestinazione))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosto))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkIscritto)
                    .addComponent(lblIscritto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCercaGita)
                    .addComponent(btnCercaPerGita)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(btnSvuotaCampi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSvuotaTutti)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSvuotaRecordSelezionato))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeGitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeGitaActionPerformed

    private void txtDestinazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinazioneActionPerformed

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        inserisciRecord();
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        if (ultimoRecordInserito.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nessun record inserito.");
        } else {
        txtArea.setText(ultimoRecordInserito);
    }
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void chkIscrittoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIscrittoActionPerformed
        txtArea.setText("");
    }//GEN-LAST:event_chkIscrittoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCercaPerGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaPerGitaActionPerformed
        cercaPerGita();
    }//GEN-LAST:event_btnCercaPerGitaActionPerformed

    private void btnLeggiTuttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeggiTuttiActionPerformed
            leggiTutti();
    }//GEN-LAST:event_btnLeggiTuttiActionPerformed

    private void btnSvuotaRecordSelezionatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvuotaRecordSelezionatoActionPerformed
        String nomeGita = jComboBox2.getSelectedItem() != null
            ? jComboBox2.getSelectedItem().toString().trim()
            : "";

    if (nomeGita.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selezionare una gita da eliminare.");
        return;
    }

    int scelta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Vuoi davvero eliminare la gita \"" + nomeGita + "\"?",
            "Conferma",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (scelta != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    try {
        boolean eliminata = gestione.eliminaGita(nomeGita);

        if (eliminata) {
            caricaComboGite();
            txtArea.setText("La gita \"" + nomeGita + "\" è stata eliminata.");
            if (ultimoRecordInserito.contains(nomeGita)) {
                ultimoRecordInserito = "";
            }
        } else {
            txtArea.setText("Nessuna gita trovata.");
        }

    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Errore: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnSvuotaRecordSelezionatoActionPerformed

    private void btnSvuotaTuttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvuotaTuttiActionPerformed
         int scelta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Vuoi davvero eliminare tutti i record?",
            "Conferma",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (scelta != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    try {
        gestione.svuotaFile();
        caricaComboGite();
        txtArea.setText("Tutti i record sono stati eliminati.");
        ultimoRecordInserito = "";
        svuotaCampi();
    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Errore: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnSvuotaTuttiActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnSvuotaCampiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvuotaCampiActionPerformed
        int scelta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Vuoi svuotare tutti i campi?",
            "Conferma",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (scelta == javax.swing.JOptionPane.YES_OPTION) {
        svuotaCampi();
        txtArea.setText("");
        txtNome.requestFocus();
    }
    }//GEN-LAST:event_btnSvuotaCampiActionPerformed
     private void inserisciRecord() {
    try {
        String nome = txtNome.getText().trim();
        String cognome = txtCognome.getText().trim();
        String classe = txtClasse.getText().trim();
        String nomeGita = txtNomeGita.getText().trim();
        String dest = txtDestinazione.getText().trim();
        String costoTesto = txtCosto.getText().trim();

        if (nome.isEmpty() || cognome.isEmpty() || classe.isEmpty()
                || nomeGita.isEmpty() || dest.isEmpty() || costoTesto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Compilare tutti i campi.");
            return;
        }

        double costo = Double.parseDouble(costoTesto);
        boolean iscritto = chkIscritto.isSelected();

        Studente s = new Studente(nome, cognome, classe, iscritto);
        Gita g = new Gita(nomeGita, dest, costo);

        if (gestione.studenteGiaInseritoNellaGita(s, nomeGita)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "L'alunno è già stato inserito nella gita \"" + nomeGita + "\".");
            return;
        }

        gestione.salvaRecord(s, g);

        ultimoRecordInserito = "Record inserito:\n" + s + "\n" + g;
        txtArea.setText(ultimoRecordInserito);
        caricaComboGite();
        preparaNuovoStudente();

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Il costo deve essere un numero.");
    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Errore nel salvataggio: " + ex.getMessage());
    }
}

    private void leggiTutti() {
        try {
            java.util.ArrayList<Gita> gite = gestione.leggiTutti();
            if (gite.isEmpty()) { txtArea.setText("Nessun record trovato."); return; }
            StringBuilder sb = new StringBuilder();
            for (Gita g : gite) {
                sb.append("=== ").append(g).append(" ===\n");
                for (Studente s : g.getStudentiPartecipanti())
                    sb.append("  ").append(s).append("\n");
                sb.append("\n");
            }
            txtArea.setText(sb.toString());
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Errore in lettura: " + ex.getMessage());
        }
    }

    private void cercaPerGita() {
    String nomeGita = jComboBox1.getSelectedItem() != null
            ? jComboBox1.getSelectedItem().toString().trim()
            : "";

    if (nomeGita.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selezionare una gita.");
        return;
    }

    try {
        java.util.ArrayList<Studente> studenti = gestione.cercaStudentiPerGita(nomeGita);

        if (studenti.isEmpty()) {
            txtArea.setText("Nessuno studente trovato per: " + nomeGita);
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Studenti iscritti a \"").append(nomeGita).append("\":\n\n");

        for (Studente s : studenti) {
            sb.append("  ").append(s).append("\n");
        }

        txtArea.setText(sb.toString());

    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Errore in lettura: " + ex.getMessage());
    }
}

    private void svuotaCampi() {
    txtNome.setText("");
    txtCognome.setText("");
    txtClasse.setText("");
    txtNomeGita.setText("");
    txtDestinazione.setText("");
    txtCosto.setText("");
    chkIscritto.setSelected(true);
    }
    
    private void caricaComboGite() {
    try {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();

        java.util.ArrayList<Gita> gite = gestione.leggiTutti();

        for (Gita g : gite) {
            jComboBox1.addItem(g.getNome());
            jComboBox2.addItem(g.getNome());
        }

    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Errore nel caricamento gite: " + ex.getMessage());
    }
} 
    
    private void preparaNuovoStudente() {
    txtNome.setText("");
    txtCognome.setText("");
    txtClasse.setText("");
    chkIscritto.setSelected(true);
    txtNome.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameGita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCercaPerGita;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnInserisci;
    private javax.swing.JButton btnLeggiTutti;
    private javax.swing.JButton btnSvuotaCampi;
    private javax.swing.JButton btnSvuotaRecordSelezionato;
    private javax.swing.JButton btnSvuotaTutti;
    private javax.swing.JCheckBox chkIscritto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCercaGita;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDestinazione;
    private javax.swing.JLabel lblIscritto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeGita;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDestinazione;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeGita;
    // End of variables declaration//GEN-END:variables
}
